### ISSUE TITLE
Stellar XDR sometimes doesn't get submitted to the ledger when submitting the transaction

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect_wallet#192]
![photo_2022-10-25 11 27 04](https://user-images.githubusercontent.com/31733464/197737267-79a45b80-f405-4aff-9e57-8a02f8582dff.jpeg)

**Comment by LennertDefauw1** [comment]
## Current problem

When there is a lot of traffic on the Public Stellar Chain, most of the times our transaction doesn't get submitted within 60 seconds which results in a 504 Gateway Timeout Error

result:

```
{
    "type": "https://stellar.org/horizon-errors/timeout",
    "title": "Timeout",
    "status": 504,
    "detail": "Your request timed out before completing.  Please try your request again. If you are submitting a transaction make sure you are sending exactly the same transaction (with the same sequence number)."
}
```

This is most likely due our submitted transaction is not getting into the ledger because the Stellar blockchain has a lot of traffic.


## Current flow

There are 2 services involved in this process. 

- Initialization service in typescript
- Activation service for creating a Stellar wallet on Mainnet

What the initialization service is doing following steps:
- Generating a random Stellar KeyPair
- Taking the Public Key of the KeyPair, and post is the activation service (https://github.com/threefoldfoundation/tft-stellar/blob/master/ThreeBotPackages/activation_service/actors/activation_service.py)
- Now we go on the the activation service
- Activation service creates a new Stellar transaction including:
   - creation of Stellar Wallet with the given address
   - Add the necessary trustlines to support TFT transactions
   - Base fee
   - TImeout
- When the transaction is built, the transaction gets signed with the foundation wallet KeyPair (All these actions are needec in the activation service because creating a Stellar Wallet requires XLM which is funded by ThreeFold)
- The Transaction is getting transformed to XDR output format, and returns the XDR in the response
- Our typescript service retrieves the XDR, converts it to a new Transaction and signs the Transaction with the random generated KeyPair secret key
- This transaction is getting submitted to the Stellar blockchain (https://horizon.stellar.org)

The creation of wallet always fails in the last step: submitting the transaction to the chain. 

This can change from moment to moment, when the ledger has a lot of load, the  transaction will timeout. When there is not that much traffic: the transaction will be submitted and the wallet will be created.

Because this, the matter of how much traffic there is on the chain will result in whether or not successfully creating a wallet

## Possible solutions

### Improve the retry system

In the current implementation, when the transaction got timed out, we are required to send a new request to the activation service to obtain a new Transaction. This is because every transaction has a TTL of 60 seconds, so if we would store the XDR object and just retry the submit call, it will always fail because the transaction gets outdated.

What we can do is maybe wait a minute, hoping that there is not much load on the Stellar network, asking a new XDR from the activation service and submitting it again. But this can be very time consuming and not that user friendly since creating a wallet on this way can take multiple minutes.


### Increase the base fee? 

According to the Stellar docs, increasing the base fee can help improving the priority of the transaction. But if we really want to do this, we will have to update the activation_service for this, since we can't update the Transaction fee at our side. 

https://github.com/stellar/new-docs/blob/master/content/api/errors/http-status-codes/horizon-specific/timeout.mdx


### Increase the timeout?

I'm not sure if this is a good decision, but currently the transaction timeout is set to 60 seconds, maybe if we increase this part a bit, we can obtain more successes of our transaction submissions. This also would require a change in the activation service




@robvanmieghem , what are your thoughts on this?

**Comment by robvanmieghem** [comment]
I'll start with increasing the fee: https://github.com/threefoldfoundation/tft-stellar/issues/452

**Comment by robvanmieghem** [comment]
Released a new version, still needs deployment: https://github.com/threefoldtech/tf_operations/issues/1239

**Comment by robvanmieghem** [comment]
Deployed the new version to production

**Comment by TullysInc** [comment]
Hello @robvanmieghem,

We have a farmer reporting the issue continues to persist. You can view details here: https://github.com/threefoldtech/tf_support/issues/394

**Comment by robvanmieghem** [comment]
https://github.com/threefoldtech/tf_support/issues/394#issuecomment-1303128495

**Comment by robvanmieghem** [comment]
As https://github.com/threefoldtech/tf_support/issues/394 is closed, I'm closing this issue too
